function createfigure(X1, Y1, X2, Y2, ytext)
%CREATEFIGURE(X1, Y1, X2, Y2)
%  X1:  vector of x data
%  Y1:  vector of y data
%  X2:  vector of x data
%  Y2:  vector of y data

%  Auto-generated by MATLAB on 31-May-2017 12:40:13

% Create figure
figure1 = figure('Color',[1 1 1]);

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create plot
plot(X1,Y1,'DisplayName','Proposed','MarkerSize',12,'Marker','x',...
    'LineWidth',2,...
    'Color',[0 0 1]);

% Create plot
plot(X2,Y2,'DisplayName','Original','MarkerSize',12,'Marker','+',...
    'LineWidth',2,...
    'Color',[1 0 1]);

% Create xlabel
xlabel({'Number of Active Nodes'});

% Create ylabel
%ylabel({'CDF'});
ylabel(ytext);

box(axes1,'on');
% Set the remaining axes properties
set(axes1,'FontSize',16,'LineWidth',2,'XGrid','on','YGrid','on');
% Create legend
legend1 = legend(axes1,'show');
set(legend1,...
    'Position',[0.153125 0.811904761904763 0.186607142857143 0.094047619047619]);

